version: '3'
services:
  fights-service:
    build:
      context: ./services/fights-service
      dockerfile: ./dev.Dockerfile
    command: 'npm start'
    volumes:
      - './services/fights-service/src:/var/www/app/current/src'
    environment:
      - NODE_ENV=development
      - 'APP_NAME=fights-service'
      - 'APP_HOST=https://localhost'
      - APP_URL_PREFIX=/api/v1
      - APP_PORT=443
      - TLS_KEY_PATH=.ssl/server.key
      - TLS_CERT_PATH=.ssl/server.crt
      - 'AUTH_ISSUER=https://joshuaw.auth0.com/'
      - 'AUTH_AUDIENCE=https://nestjs-heros.com'
      - 'AUTH_JWKS_URL=https://joshuaw.auth0.com/.well-known/jwks.json'
      - REDIS_HOST=heros-redis
      - REDIS_PORT=6379
      - MONGO_HOST0=heros-mongodb
      - MONGO_PORT=27017
      - MONGO_USER=
      - MONGO_PASS=
      - 'MONGO_DB=heros_db'
    depends_on:
      - heros-redis
      - heros-mongodb
    ports:
      - '5433:443'
    networks:
      - app-tier
      - server-tier
  gateway-service:
    build:
      context: ./services/gateway-service
      dockerfile: ./dev.Dockerfile
    command: 'npm start'
    volumes:
      - './services/gateway-service/src:/var/www/app/current/src'
    environment:
      - NODE_ENV=development
      - 'APP_NAME=gateway-service'
      - 'APP_HOST=https://localhost'
      - APP_URL_PREFIX=/api/v1
      - APP_PORT=443
      - TLS_KEY_PATH=.ssl/server.key
      - TLS_CERT_PATH=.ssl/server.crt
      - 'AUTH_ISSUER=https://joshuaw.auth0.com/'
      - 'AUTH_AUDIENCE=https://nestjs-heros.com'
      - 'AUTH_JWKS_URL=https://joshuaw.auth0.com/.well-known/jwks.json'
      - REDIS_HOST=heros-redis
      - REDIS_PORT=6379
      - MONGO_HOST0=heros-mongodb
      - MONGO_PORT=27017
      - MONGO_USER=
      - MONGO_PASS=
      - 'MONGO_DB=heros_db'
    depends_on:
      - heros-redis
      - heros-mongodb
    ports:
      - '4433:443'
    networks:
      - app-tier
      - server-tier
  heros-service:
    build:
      context: ./services/heros-service
      dockerfile: ./dev.Dockerfile
    command: 'npm start'
    volumes:
      - './services/heros-service/src:/var/www/app/current/src'
    environment:
      - NODE_ENV=development
      - 'APP_NAME=heros-service'
      - 'APP_HOST=https://localhost'
      - APP_URL_PREFIX=/api/v1
      - APP_PORT=443
      - TLS_KEY_PATH=.ssl/server.key
      - TLS_CERT_PATH=.ssl/server.crt
      - 'AUTH_ISSUER=https://joshuaw.auth0.com/'
      - 'AUTH_AUDIENCE=https://nestjs-heros.com'
      - 'AUTH_JWKS_URL=https://joshuaw.auth0.com/.well-known/jwks.json'
      - REDIS_HOST=heros-redis
      - REDIS_PORT=6379
      - MONGO_HOST0=heros-mongodb
      - MONGO_PORT=27017
      - MONGO_USER=
      - MONGO_PASS=
      - 'MONGO_DB=heros_db'
    depends_on:
      - heros-redis
      - heros-mongodb
    ports:
      - '7433:443'
    networks:
      - app-tier
      - server-tier
  teams-service:
    build:
      context: ./services/teams-service
      dockerfile: ./dev.Dockerfile
    command: 'npm start'
    volumes:
      - './services/teams-service/src:/var/www/app/current/src'
    environment:
      - NODE_ENV=development
      - 'APP_NAME=teams-service'
      - 'APP_HOST=https://localhost'
      - APP_URL_PREFIX=/api/v1
      - APP_PORT=443
      - TLS_KEY_PATH=.ssl/server.key
      - TLS_CERT_PATH=.ssl/server.crt
      - 'AUTH_ISSUER=https://joshuaw.auth0.com/'
      - 'AUTH_AUDIENCE=https://nestjs-heros.com'
      - 'AUTH_JWKS_URL=https://joshuaw.auth0.com/.well-known/jwks.json'
      - REDIS_HOST=heros-redis
      - REDIS_PORT=6379
      - MONGO_HOST0=heros-mongodb
      - MONGO_PORT=27017
      - MONGO_USER=
      - MONGO_PASS=
      - 'MONGO_DB=heros_db'
    depends_on:
      - heros-redis
      - heros-mongodb
    ports:
      - '8433:443'
    networks:
      - app-tier
      - server-tier
  villains-service:
    build:
      context: ./services/villains-service
      dockerfile: ./dev.Dockerfile
    command: 'npm start'
    volumes:
      - './services/villains-service/src:/var/www/app/current/src'
    environment:
      - NODE_ENV=development
      - 'APP_NAME=villains-service'
      - 'APP_HOST=https://localhost'
      - APP_URL_PREFIX=/api/v1
      - APP_PORT=443
      - TLS_KEY_PATH=.ssl/server.key
      - TLS_CERT_PATH=.ssl/server.crt
      - 'AUTH_ISSUER=https://joshuaw.auth0.com/'
      - 'AUTH_AUDIENCE=https://nestjs-heros.com'
      - 'AUTH_JWKS_URL=https://joshuaw.auth0.com/.well-known/jwks.json'
      - REDIS_HOST=heros-redis
      - REDIS_PORT=6379
      - MONGO_HOST0=heros-mongodb
      - MONGO_PORT=27017
      - MONGO_USER=
      - MONGO_PASS=
      - 'MONGO_DB=heros_db'
    depends_on:
      - heros-redis
      - heros-mongodb
    ports:
      - '9433:443'
    networks:
      - app-tier
      - server-tier
  heros-redis:
    image: 'redis:alpine'
    container_name: heros-redis
    ports:
      - '6379'
    networks:
      - server-tier
  heros-mongodb:
    image: 'mongo:latest'
    container_name: heros-mongodb
    ports:
      - '27017:27017'
    volumes:
      - 'heros-mongodb-data:/data/db'
    networks:
      - server-tier
volumes:
  heros-mongodb-data: null
networks:
  app-tier: null
  server-tier: null
